### PR TITLE
Add API section to every environment with links to source code

### PR DESCRIPTION
**Pull request by elliottower**
I have always found it annoying that there was no direct way to view the full source code from being on an environment page, so I added this. Thanks to the previous PR that gives links to source code for API documentation, this now allows there to be links to source code at the bottom of the file.

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue), Depends on # (pull request)

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

### Screenshots

> Please attach before and after screenshots of the change if applicable.
> To upload images to a PR -- simply drag and drop or copy paste.

# Checklist:

- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have run `pytest -v` and no errors are present.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I solved any possible warnings that `pytest -v` has generated that are related to my code to the best of my knowledge.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
This is an interesting point for gymnasium, I would consider changing the documentation to use the autoclass reference for the environment class

**Comment by elliottower** [comment]
> This is an interesting point for gymnasium, I would consider changing the documentation to use the autoclass reference for the environment class

I tried a few others like automodule for the entire file (had all the comments at the top and was very messy) and tried specific methods but this was the simplest looking and most straightforward imo. There aren’t really proper classes for each environment as they are defined only as raw env and env, so that’s all I had to work with

**Comment by elliottower** [comment]
Looks like gymnasium is a bit more structured with environments named CartPoleEnv so that would probably be more user friendly than raw_env. I also wasn’t sure if it should be API or Source Code or something, but the other pages like AEC or parallel api pages have their auto docs under an API header at the bottom

**Comment by elliottower** [comment]
I merged this but the build-docs test seems to not have ran and is now failing, is it possible to enable this on every PR?

**Pull request merged**
