### PR TITLE
Add seed parameter to reset() [DO NOT MERGE YET]

### PR DESCRIPTION
**Pull request by elbamos**
And call self.seed(seed) in non-deterministic environments if the seed parameter is set. 

Addresses #581 .

### CODE REVIEW

**Comment by benblack769** [comment]
The documentation and api tests also need to be changed to completely resolve #581.

**Comment by benblack769** [comment]
Let me know if you need any help with this.

**Comment by elbamos** [comment]
I can address the issue with the wrappers and the base method; can you take a look at what’s required in terms of updated documentation and api tests?

**Comment by benblack769** [comment]
I can take a look, sure. Note that once you change the wrappers to not forward the seed() method, some of the tests will fail.

**Comment by elbamos** [comment]
My most recent push propogates the seed logic to the wrappers and fixes some of the seed api tests.  Most tests pass -- however the `atari` and `magent` tests fail on a type error, that `reset()` doesn't have a seed parameter. 

I'm not sure why that is - the environments for atari and magent are appropriately catching the call to `reset()` and calling `seed()` on themselves rather than passing it to the underlying external environment. 

Any hints?

**Comment by elbamos** [comment]
I've fixed the wrappers, updated the seed tests, and added deprecation warnings to the base seed() method. All tests should pass.  I'm not sure what needs to be done with documentation?

**Comment by elbamos** [comment]
It looks that this PR is now clearing all tests internal to PettingZoo. It's getting stuck on the 13-lines test, because that depends on wrappers imported from supersuit that haven't been updated for the changed seed api. 

How do we move forward?

**Comment by jkterry1** [comment]
@elbamos could you please create a PR to supersuit to add support for this?

**Comment by elbamos** [comment]
I made an attempt: https://github.com/Farama-Foundation/SuperSuit/pull/123 but trying to update both repos at the same time really complicates testing and validation.  

Considering that SuperSuit depends on PettingZoo, I suggest taking out of PettingZoo any dependencies on SuperSuit, which I think are limited to the use of SuperSuit wrappers in the 13-lines test.

**Comment by benblack769** [comment]
@elbamos Yeah, on reflection, I think adding the 13 lines test was a mistake (my mistake, to be specific). Feel free to remove it.

**Comment by elbamos** [comment]
This should be good to merge now.

**Comment by jkterry1** [comment]
I just want to note here that this should not be merged until the version of Gym with this fix is released. This release will most likely take another month (or longer if more goes wrong). Given the large number of environment fixes coming in right now, we likely will want to cut a PettingZoo release before then.

**Comment by benblack769** [comment]
@elbamos Just made a few changes to the tests and base environment stuff here, generally looked good, all the environments were updated and all that.

**Comment by benblack769** [comment]
Actually, @elbamos I found one issue with the implementation that I fixed. 

the logic:

```
if seed:
     self.seed(seed)
```

doesn't work if the `seed=0`. So I had to change them to 

```
if seed is not None:
     self.seed(seed)
```

**Comment by jjshoots** [comment]
Closing because #669 handles this

**Pull request closed without merging**
