### PR TITLE
Hanabi Integration

### PR DESCRIPTION
**Pull request by dissendahl**
- Hanabi, integrated from official repo as git submodule. 
- See hanabi/README.md for how to pull and setup git submodule.
- See documentation within class for full information.
- Debugged and E2E tested with unittest, including api test as part of the unit tests.

- CHANGE REQUEST: Add typing annotation in utils/env.py, see last commit.

### CODE REVIEW

**Comment by dissendahl** [comment]
@weepingwillowben and @justinkterry : Thanks for reviewing! 

1. I will update the env to work with a default game configuration. @weepingwillowben: So I understoud now that envs should work without config. But is it okay to pass them parameters or is this not wanted all?
2. I will remove the git submodule thing and the belonging readme. 
3. Take a look at the merge conflict.

**Comment by weepingwillowben** [comment]
The goal is something like this:

```
class env(AECEnv):

    metadata = {'render.modes': ['human']}

    def __init__(self, seed=None, spawn_rate=20, num_archers=2, num_knights=2, killable_knights=True, killable_archers=True, pad_observation=True, max_frames=900):
```

**Comment by weepingwillowben** [comment]
So the environment will have parameters, but they will all have a default value.

**Comment by justinkterry** [comment]
@clemens4321 Please move the type hints from the AECEnv class specifically to hanabi

**Comment by dissendahl** [comment]
Removed the branch, therefore have to reopen pull request.

**Pull request closed without merging**
