### PR TITLE
Truncation Update

### PR DESCRIPTION
**Pull request by jjshoots**
# About

This aims to do part 1 of #769.

`done` -> `termination` and `truncation`
    - The singular `done` signal has been changed to a `termination` and `truncation` signal, where `termination` dictates that the environment has ended due to meeting certain conditions, and `truncation` dictates that the environment has ended due to exceeding the time/frame limit

## Progress

The road plan for this update is as follows:

1. Truncation/Termination update
    - [x] MPE
    - [x] MAgent
    - [x] Butterfly
    - [x] Atari
    - [x] SISL
    - [x] Classic
2. Tests update
    - [x] `all_parameter_combs_test.py`
        - [x] MPE
        - [x] MAgent
        - [x] Butterfly
        - [x] Atari
        - [x] SISL
        - [x] Classic
    - [x] `doc_example_test.py`
    - [x] `print_test.py`
    - [ ] `pytest_runner_test.py`
    - [x] `specific_env_test.py`
    - [ ] `unwrapped_test.py`
    - [x] `variable_env_test.py`

### CODE REVIEW

**Comment by WillDudley** [comment]
@jjshoots Any idea why prospector fails? Works on mine locally

**Comment by WillDudley** [comment]
lgtm if prospector goes

**Comment by jjshoots** [comment]
I'll need to get back and fix the conflicts, will merge once that's done. Thanks for the review!

**Comment by WillDudley** [comment]
lgtm

**Pull request merged**
