### PR TITLE
Update agilerl version and simplified CNN definition

### PR DESCRIPTION
**Pull request by nicku-a**
# Description

Updates agilerl version in tutorials, and also simplifies kernel size definition for multi-agent CNNs.

Fixes # (issue), Depends on # (pull request)

## Type of change

- This change requires a documentation update

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have run `pytest -v` and no errors are present.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I solved any possible warnings that `pytest -v` has generated that are related to my code to the best of my knowledge.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by nicku-a** [comment]
FYI failing tests correspond to other areas of the codebase (chess test and knights archers zombies docs)

**Comment by dm-ackerman** [comment]
Hi, I saw the update to AgileRL broke the tutorial a few days ago. Thanks for fixing this! Would you mind updating your branch to the current master? That should fix the broken tests so it can be merged. There will probably be a merge conflict because I pinned the agilerl version to 0.1.19 to stop the errors until the tutorial was fixed. But I think everything else should work fine.

**Comment by nicku-a** [comment]
Sorry for the delay @dm-ackerman - should be good to go!

**Review by jjshoots — APPROVED** [review]
Looks reasonable to me. Thanks!

**Pull request merged**
