### PR TITLE
Added rgb_array to capture_stdout

### PR DESCRIPTION
**Pull request by Rohan138**
This was causing the MCMES SSD errors.

### CODE REVIEW

**Comment by benblack769** [comment]
So generally speaking this wrapper is only meant to wrap environments which print text to the terminal, like the pettingzoo chess environment does. What environment did it cause an issue with in this case?

**Comment by Rohan138** [comment]
Ah, that makes sense. I was getting the error with the SSD environments. However, the docs on the (PettingZoo environment creation)[https://www.pettingzoo.ml/environment_creation#example-custom-environment] page seem a little misleading in recommending them for all environments, or maybe that's just me misreading them.

**Comment by Rohan138** [comment]
@benblack769 do you want to merge this or close it? I'm fine either way. It might help if there's a weird environment that both renders and prints to console.

**Comment by benblack769** [comment]
That makes sense. That documentation is certainly misleading.

**Comment by benblack769** [comment]
I think this can be merged anyways, but its good to know where things went wrong.

**Comment by benblack769** [comment]
So a simpler, probably better logic for this change would simply be:

```
        if mode == "ansi":
            with capture_stdout() as stdout:

                super().render("human")

                val = stdout.getvalue()
            return val
        else:
            return super().render(mode)
```

**Pull request merged**
