### PR TITLE
Removed white spaces in Magent rendering

### PR DESCRIPTION
**Pull request by rodrigodelazcano**
Issue #282

### CODE REVIEW

**Comment by weepingwillowben** [comment]
text_overlay

The gray border overlaps with the text (this screenshot is from the battle environment. This is not ideal.

**Comment by rodrigodelazcano** [comment]
> text_overlay
> 
> The gray border overlaps with the text (this screenshot is from the battle environment. This is not ideal.

I will have a look at it

**Comment by weepingwillowben** [comment]
The banner is a little  on the small side, but I'm OK with it

magent

Is this OK? @justinkterry

**Comment by justinkterry** [comment]
I actually like it

**Pull request merged**
