### PR TITLE
Update gymnasium dependencies to 1.0.0a1

### PR DESCRIPTION
**Pull request by pseudo-rnd-thoughts**
# Description

Updates Gymnasium to 1.0.0a1

### CODE REVIEW

**Comment by pseudo-rnd-thoughts** [comment]
It looks like SB3 needs to be updated which will be done in https://github.com/DLR-RM/stable-baselines3/pull/1837

**Comment by chrisyeh96** [comment]
Now that SB3 has been updated to Gymnasium v1.0 (https://github.com/DLR-RM/stable-baselines3/pull/1837), can PettingZoo finally be updated to also support Gymnasium v1.0?

**Comment by David-GERARD** [comment]
@pseudo-rnd-thoughts @chrisyeh96 support for Gymnasium v1.0 is on my task list, should be coming ASAP.

**Review by David-GERARD — APPROVED** [review]

**Comment by David-GERARD** [comment]
The connect_four failing ci test have been addressed in #1242, clear to merge.

**Pull request merged**
