### PR TITLE
Python 3.10

### PR DESCRIPTION
**Pull request by jkterry1**

### CODE REVIEW

**Comment by jkterry1** [comment]
See https://github.com/openai/gym/pull/2493

**Comment by jkterry1** [comment]
(the issue is the tests on the 13 line tutorial are failing)

**Comment by benblack769** [comment]
Update: if you try to install pettingzoo on python 3.10, you end up getting pettingzoo==1.3.4, i.e. the last version where there was no maximum python version.

Given that, this effort should probably be prioritized.

**Comment by jkterry1** [comment]
I mean its waiting on you to fix tests not me

**Comment by benblack769** [comment]
Oh.

**Pull request merged**
