### PR TITLE
Update RLlib tutorials

### PR DESCRIPTION
**Pull request by elliottower**
# Description

This PR updates the RLlib tutorials, which are written for a previous version of pettingzoo using gym rather than gymnasium.

Fixes # (issue), Depends on # (pull request)

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

### Screenshots

> Please attach before and after screenshots of the change if applicable.

# Checklist:

- [ ] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have run `pytest -v` and no errors are present.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I solved any possible warnings that `pytest -v` has generated that are related to my code to the best of my knowledge.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by elliottower** [comment]
Need to fix the leduc_holdem code as DQN I believe still has issues (https://github.com/ray-project/ray/issues/32910), could replace with PPO maybe?

**Comment by jjshoots** [comment]
There doesn't appear to be tests for these right?

**Review by jjshoots — APPROVED** [review]
I can't comment on the RLLib fixes --- I'm not familiar enough with its intricacies.

That said, everything else looks good to me, so if you think the RLLib stuff is good to you, feel free to get this merged.

**Comment by elliottower** [comment]
Closing this in favor of separate PRs for simplicity.

**Pull request closed without merging**
