### PR TITLE
Tests duplicated deleted from parametrized_envs

### PR DESCRIPTION
**Pull request by GiovanniGrotto**
# Description

I deleted all the repeted lines in ```parametrized_envs``` from ```all_parameters_combs_tests.py```, and changed lines where the kwargs where matching with default arguments with an empty dict, so now the test will run with default args also if they will be changes in __init__ func.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### Screenshots

This is an exmaple of what I changed, the first highlighted line now has an empty dict instead of hand_size=5 and the second and third lines have been deleted.
Immagine 2023-08-19 153353

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [x] I have run `pytest -v` and no errors are present.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I solved any possible warnings that `pytest -v` has generated that are related to my code to the best of my knowledge.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by elliottower — APPROVED** [review]
Looks good to me, thanks for taking the time to fix this. Curious what the speedup will be in the CI. If you could also try to cross reference with the pytest runner file and see if we actually need both of these files (my guess is that was created first and this is the more comprehensive version of it, you could check git blame to figure out when each was created and stuff like that as well)

**Comment by GiovanniGrotto** [comment]
> Looks good to me, thanks for taking the time to fix this. Curious what the speedup will be in the CI. If you could also try to cross reference with the pytest runner file and see if we actually need both of these files (my guess is that was created first and this is the more comprehensive version of it, you could check git blame to figure out when each was created and stuff like that as well)

Yes I'll check in the next days an try to speed up test as much as possible, I can also check Gymnasium wrapper for max_cycles

**Comment by elliottower** [comment]
Looks good, only thing I'd say is try to at least do two parameter combinations per environment (I imagine the test will take about the same amount of time if you just remove the pytest runner test and do this, because most envs are already being run twice with the two files)

**Comment by elliottower** [comment]
Good stuff, the tests are now 15 mins instead of 30 mins

**Pull request merged**
