### PR TITLE
Replaced geek.ai logo with block pattern in gather per #605

### PR DESCRIPTION
**Pull request by kkahadze**

### CODE REVIEW

**Comment by jkterry1** [comment]
Could you please bump the version in this?

**Comment by jkterry1** [comment]
and can you please put a gif in here so people can see the change?

**Comment by kkahadze** [comment]
Here is the change.
gather_v4

**Comment by kkahadze** [comment]
> Could you please bump the version in this?

To do this, do I just change the filename and every mention of "gather_v3" to "gather_v4"?

**Comment by benblack769** [comment]
@kkahadze Basically, yes. Just make sure you also replace references in the documentation and tests.

**Comment by kkahadze** [comment]
That should be everything.

**Comment by jkterry1** [comment]
@kkahadze can you please fix the merge conflict?

**Comment by kkahadze** [comment]
@jkterry1 Shouldn't be a problem. It is blocking me right now though because I need write access.

**Comment by jkterry1** [comment]
What do you mean you need write access? It's your own fork on github

**Comment by kkahadze** [comment]
@jkterry1 Ah I see. My mistake. This shouldn't have any conflicts.

**Comment by kkahadze** [comment]
@jkterry1 Is there something I need to change for the Python tests to pass? I though I merged the changes correctly.

**Comment by jkterry1** [comment]
Look at the code after the merge

**Comment by jkterry1** [comment]
@kkahadze can you please fix the tests?

**Comment by jkterry1** [comment]
Just look at the file here, you handled the merge conflict here: https://github.com/Farama-Foundation/PettingZoo/blob/8747c99da73098de13227805a8e1f1b4561d637c/pettingzoo/magent/gather_v4.py

**Pull request merged**
