### PR TITLE
Fix add render tests PR to eliminate merge conflicts and not fail tests

### PR DESCRIPTION
**Pull request by elbamos**
The large number of commits here is due to rebasing to eliminate the merge conflicts.

### CODE REVIEW

**Comment by benblack769** [comment]
@elbamos 

1. Do you know why tests are not running in this PR?
2. What merge conflicts are you trying to avoid? If you fix the render tests in this PR, the other PR will simply be closed.

**Comment by benblack769** [comment]
I got #517 to be almost working I think. Let me know if anything here is worth including, or if this can be closed.

**Comment by elbamos** [comment]
I had to make changes to the return value of the render function of several environments to clear these tests. That’s the change reflected in this pr. Take a look at the commit descriptions. 

As for why tests aren’t running, I presume you mean in CI, I have no idea - I haven’t looked at the CI configuration at all. Tests do clear when pytest is run manually.

**Comment by benblack769** [comment]
I would avoid rebasing in the future, it makes this kind of impossible to review. I would just make a normal merge conflict resolution.

**Pull request closed without merging**
