### PR TITLE
Update RLlib examples for Ray 2.0.0

### PR DESCRIPTION
**Pull request by Rohan138**
# Description

Ray+RLlib 2.0.0 is currently being released as an `rc0`. I've updated all four RLlib examples to work with the new paths for algorithms, renamed imports, etc. and migrated the `leduc_holdem` and `pistonball` examples to use RLlib's config objects API.

This PR should be kept as a draft until Ray 2.0.0 is released on PyPI (next week or so).

Fixes # (issue), Depends on # (pull request)

## Type of change

> Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

### Screenshots

> Please attach before and after screenshots of the change if applicable.
> To upload images to a PR -- simply drag and drop or copy paste.

# Checklist:

- [X] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [X] I have run `pytest -v` and no errors are present.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I solved any possible warnings that `pytest -v` has generated that are related to my code to the best of my knowledge.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jjshoots** [comment]
Hey @Rohan138, thanks a bunch for this, is this ready to merge?

**Comment by Rohan138** [comment]
Not yet-These fixes are for `ray==2.0.0`, which hasn't been released on PyPI yet. I'll un-draft this PR when it's released next week.

**Comment by pseudo-rnd-thoughts** [comment]
Pypi release for 2.0 is available however as it is a pre release, are we certain we want to update the tutorial or just make a new tutorial for 2.0

**Comment by WillDudley** [comment]
@Rohan138 Please may you add a docstring at the top of each file with all dependencies with versions, as well as the Python version used. Please also add to these docstrings a couple of sentences explaining what the file does.

The idea is someone can look at the one file, understand the gist of it, and know how to reproduce it.

**Comment by WillDudley** [comment]
I can't wait any longer. Please add the info to the main PR or the master branch. Ask me if you don't understand.

**Pull request closed without merging**
