### PR TITLE
Update docs website to Sphinx

### PR DESCRIPTION
**Pull request by mgoulao**
# Description

Update documentation website to use Sphinx with the same template as gym.

### CODE REVIEW

**Comment by jjshoots** [comment]
Holy cow, 308 files modified 😅. @mgoulao, could you perhaps fix precommit tests?

**Comment by mgoulao** [comment]
Apologies for the size of the PR, most changes are removal of files that are not needed anymore plus some renames and directory structure changes. You can compare the current version [www.pettingzoo.ml](https://www.pettingzoo.ml) with the Sphinx version using my deploy [mgoulao.github.io/PettingZoo](https://mgoulao.github.io/PettingZoo).

**Comment by WillDudley** [comment]
@jjshoots

**Comment by WillDudley** [comment]
Should work with https://github.com/Farama-Foundation/PettingZoo/pull/787 - please add these changes to the PR and see if the tests pass :)

**Comment by jjshoots** [comment]
Thanks a ton for the work @mgoulao @WillDudley

**Pull request merged**
